fixup! penang: Declare NQNfcNci app to include * So now com.nxp.nfc.nq are missing
01-20 11:18:24.551  4764  4764 D AndroidRuntime: Shutting down VM
01-20 11:18:24.552  4764  4764 E AndroidRuntime: FATAL EXCEPTION: main
01-20 11:18:24.552  4764  4764 E AndroidRuntime: Process: com.android.nfc, PID: 4764
01-20 11:18:24.552  4764  4764 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/nfc/NfcService;
01-20 11:18:24.552  4764  4764 E AndroidRuntime: at com.android.nfc.NfcService.<init>(NfcService.java:798)
01-20 11:18:24.552  4764  4764 E AndroidRuntime: at com.android.nfc.NfcApplication.onCreate(NfcApplication.java:70)
01-20 11:18:24.552  4764  4764 E AndroidRuntime: at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1326)
01-20 11:18:24.552  4764  4764 E AndroidRuntime: at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7068)
01-20 11:18:24.552  4764  4764 E AndroidRuntime: at android.app.ActivityThread.-3528170Nest(Unknown Source:0)
01-20 11:18:24.552  4764  4764 E AndroidRuntime: at android.app.ActivityThread.handleMessage(ActivityThread.java:2262)
01-20 11:18:24.552  4764  4764 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:106)
01-20 11:18:24.552  4764  4764 E AndroidRuntime: at android.os.Looper.loopOnce(Looper.java:205)
01-20 11:18:24.552  4764  4764 E AndroidRuntime: at android.os.Looper.loop(Looper.java:294)
01-20 11:18:24.552  4764  4764 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:8282)
01-20 11:18:24.552  4764  4764 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
01-20 11:18:24.552  4764  4764 E AndroidRuntime: at com.android.internal.os.RuntimeInit.run(RuntimeInit.java:554)
01-20 11:18:24.552  4764  4764 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
01-20 11:18:24.552  4764  4764 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: com.android.nfc.NfcService
01-20 11:18:24.552  4764  4764 E AndroidRuntime: ... 13 more